gym/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title=StringField('Title', validators=[DataRequired()])
    content=TextAreaField('Content', validators=[DataRequired()])
    submit=SubmitField('Post')

gym/main/routes.py
from _sqlite3 import OperationalError
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import exc
import time
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from gym import db, mongo
from gym.models import Search, Gym, Location, Post, Info
from gym.search.forms import SearchForm
from gym.search.scraper import scrape
from gym.search.maps_scraper import maps_scrape, get_place_details, abbreviation_fixer
from flask_login import login_required
from flask_pymongo import PyMongo
import json
import csv
import os

# heroku machine will store two keys, a secret one for client-side js 
# and a regular one for python since the server isnt viewable by user 
# but if you're runing locally, just use regular one so os.environ['API_KEY']

API_KEY= os.environ['SECRET_KEY']
assert API_KEY

main = Blueprint('main', __name__)
locations_coordinates = {}

@main.route("/", methods=['GET', 'POST'])
@main.route("/home", methods=['GET', 'POST'])
def home():
    form = SearchForm()
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)

    if request.method == 'POST' and form.validate():
        query = form.search.data.lower()
        range = form.range.data
        return redirect(url_for('main.search', query=query))
    return render_template('home.html', form=form, posts=posts, key=API_KEY)

@main.route("/about")
def about():
    return render_template('about.html', title='About')

@main.route("/blog")
def blog():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('blog.html', title='Blog', posts=posts)

@main.route("/coordinates", methods=['GET', 'POST'])
def send_coordinates():
    #print(locations_coordinates)
    return json.dumps({"data": locations_coordinates})

@main.route("/search/<query>", methods=['GET', 'POST'])
def search(query):
    locations_coordinates.clear()
    query=abbreviation_fixer(query)

    #initialize DB
    search=mongo.db.search
    gym = mongo.db.gym
    location = mongo.db.location
    info = mongo.db.info           

    check_searches = search.find_one({'user_input':query})

    # if this is a new search
    if check_searches == None:
            #center lat,lng are the coordinates of the gym

        center_lat, center_lng, data = maps_scrape(query)
        current_search = {'gym_id':[],'user_input':query,'lat':center_lat, 'lng':center_lng}
        search.insert_one(current_search)
        #   print(current_search['_id'])

        if data != 0:
            # for each gym that is found
            for result in data['results']:
                place_id = result['place_id']
                lat = result['geometry']['location']['lat']
                lng = result['geometry']['location']['lng']

                maps_link, gym_name, address = get_place_details(place_id)
                print(gym_name)
                # this photo reference can be used in the google places photo api
                # to get a posted picture, but it is not their logo
                # image = result['photo_reference']

                #add data to location coordinates api
                if locations_coordinates == {}:
                    locations_coordinates['center'] = [center_lat, center_lng]
                    locations_coordinates['gyms']=[{'name': gym_name, 'coordinates':[lat, lng], 'link': maps_link, 
                    'address': address}]
                else:
                    locations_coordinates['gyms'].append({'name': gym_name, 'coordinates':[lat, lng], 
                        'link': maps_link, 'address': address})

                check_gyms = gym.find_one({'name':gym_name})
                # if this is a new gym, create the Gym, a Location, and append
                if check_gyms == None:
                    current_gym = {'search_id':[current_search['_id']], 'location_id':[], 'info_id': [],'name':gym_name}
                    gym.insert_one(current_gym)

                    current_location = {'search_id':[current_search['_id']],'gym_id':current_gym['_id'],'place_id':place_id, 'name':gym_name,
                        'address':address,'link':maps_link, 'lat':lat, 'lng':lng}
                    location.insert_one(current_location)
                    current_gym['location_id'].append(current_location['_id'])
                else:
                    current_gym = check_gyms

                    if current_gym['search_id'][0] != current_search['_id']:
                        current_gym['search_id'].append(current_search['_id'])

                    check_locations = location.find_one({'address':address})
                    # if new location, create location
                    if check_locations == None:
                        current_location = {'search_id':[current_search['_id']],'gym_id':current_gym['_id'],'place_id':place_id, 'name':gym_name,   
                            'address':address,'link':maps_link, 'lat':lat, 'lng':lng}
                        location.insert_one(current_location)
                        current_gym['location_id'].append(current_location['_id'])
                        # if location exists update its search id, so we know it corresponds to this search.
                    else:
                        current_location = check_locations
                        current_location['search_id'].append(current_search['_id'])

                #add gym to search if its not there already 
                if current_gym['_id'] not in current_search['gym_id']:
                    current_search['gym_id'].append(current_gym['_id'])

                link_and_description = scrape(query, gym_name)
                link = link_and_description[0]
                description = link_and_description[1]

                
                # check gym info
                if current_gym['info_id'] == []:
                    current_info = {'search_id':[current_search['_id']], 'gym_id':current_gym['_id'], 'link':link, 'description':description, 'name':gym_name}
                    info.insert_one(current_info)
                    current_gym['info_id'].append(current_info['_id'])
                # else if it has info, if info is different add a new info
                else:
                    #links = [i.link for i in gym.info]
                    check_info = info.find_one({'link':link})
                    # if info is new, create new Info object
                    if check_info == None:
                        current_info = {'search_id':[current_search['_id']], 'gym_id':current_gym['_id'],'link':link, 'description':description, 'name':gym_name}
                        info.insert_one(current_info)
                        current_gym['info_id'].append(current_info['_id'])
                    # if info is right, just update search id
                    else:
                        current_info = check_info
                        if current_search['_id'] not in current_info['search_id']:
                            current_info['search_id'].append(current_search['_id'])

                info.save(current_info)
                gym.save(current_gym)
                location.save(current_location)

    else:
        current_search = check_searches
        center_lat = current_search['lat']
        center_lng = current_search['lng']
        # even though the search has been done before, we still need to update info
        for gym_id in current_search['gym_id']:
            # update
            current_gym = gym.find_one({'_id':gym_id})
            #send coordinates api
            for location_id in current_gym['location_id']:
                current_location = location.find_one({'_id':location_id})
                if current_search['_id'] in current_location['search_id']: 
                    if locations_coordinates == {}:
                        locations_coordinates['center'] = [center_lat, center_lng]
                        locations_coordinates['gyms']=[{'name': current_gym['name'], 'coordinates':[current_location['lat'], current_location['lng']], 
                        'link': current_location['link'], 'address': current_location['address']}]
                    else:   
                        locations_coordinates['gyms'].append({'name': current_gym['name'], 
                            'coordinates':[current_location['lat'], current_location['lng']], 'link': current_location['link'], 
                            'address': current_location['address']})

    search.save(current_search)
    gyms = current_search['gym_id']

    if len(gyms) == 0:
        flash('Did not find any gyms passes! This can either be because there are none or our servers are down.' + 
            ' Please try again at a later time.', 'danger')
    elif len(gyms) == 1:
        flash('Found {} pass at this gym by {}!'.format(len(gyms), query), 'success')
    else:
        flash('Found {} passes at these gyms by {}!'.format(len(gyms), query), 'success')
    return render_template('results.html', title="Search Results", current_search=current_search, search=search, 
        gym=gym, info=info, location=location, key=API_KEY)


@main.route("/scrape", methods=['GET', 'POST'])
@login_required
def pre_scrape():
    #used for pre-scraping to set up db 
    with open('./gym/static/csv/short_cities_list.csv', 'r') as csv_file:
        csv_reader = csv.reader(csv_file)
        # Opens csv file with names of cities
        for line in csv_reader:
            query=line[1]+", "+line[2]+", USA"
            query=query.lower()
            print(query)

            #initialize DB
            search=mongo.db.search
            gym = mongo.db.gym
            location = mongo.db.location
            info = mongo.db.info           

            check_searches = search.find_one({'user_input':query})

gym/posts/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from gym import db
from gym.models import Post
from gym.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post',
                           form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post',
                           form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

gym/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from gym import db, bcrypt
from gym.models import User, Post
from gym.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from gym.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
#@login_required
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

gym/templates/about.html
{%extends "layout.html"%}
    
{%block content%}
<div class="col-mid-8">
   <h1>About Page</h1>
   
   	 <p>
   	Cloud Fitness is application made by <a href="http://www.columbia.edu/~km3290" target="_blank">Kevin Mao</a>, Columbia 2021 
   	and <a href="https://www.linkedin.com/in/dray-c-f-555770125" target="_blank">Dray Farley</a>, Cornell 2021. We use advanced cloud technology to bring you free gym passes, so you can focus on working out. This is currently a work in progress.
   <p>
   </div>
  
{%endblock content%}

gym/templates/blog.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

gym/templates/home.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='favicon.png') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    

    {% if title %}
        <title>Cloud Fitness- {{ title }}</title>
    {% else %}
        <title>Cloud Fitness</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Cloud Fitness</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                <a class="nav-item nav-link" href="{{ url_for('main.blog') }}">Blog</a>
            </div >
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                
              {% endif %}
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="home_container">
      <div class="row">
        <div class="col-md-box">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}

<div class="background">
<div class="overlay">
    <div class="left-box"></div>
<div class="main-box">
<form method="POST" action="">
    {{ form.hidden_tag() }}
    <fieldset class="form-group">
        <legend class="border-bottom mb-5">Work out for free</legend>
        
<!--
<div id="stage">
        <a><img src="{{ url_for('static', filename='slideshow/image1.jpg' )}}"/></a>
        <a><img src="{{ url_for('static', filename='slideshow/image2.jpg' )}}"/></a>
        <a><img src="{{ url_for('static', filename='slideshow/image3.jpg' )}}"/></a>
</div>        
-->

        <div class="nile-slider large-12 column" onload="fadeimages()">
</div>
        <div class="form-group">
            {{ form.search.label(class="search-label") }}
            {% if form.search.errors %}
                {{ form.search(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.search.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{ form.search(class="form-control form-control-lg", id='search_term') }}
                <!-- {{ form.range(class="form-control form-control-lg", id='search_term') }} -->
            {% endif %}
        </div>
    </fieldset>
    <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
    </div>
    </form>
    </div>
    <div class="left-box"></div>
</div>
    </div>
            
<!--     {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %} -->
   <script type="text/javascript">
     function activatePlacesSearch(){
      var input = document.getElementById('search_term');
      var autocomplete = new google.maps.places.Autocomplete(input);
    }
   </script>

         <script type="text/javascript">// change header image after 2 seconds
    $(document).ready(function(){
    $('.your-class').slick({
      slidesToShow: 1,
      slidesToScroll: 1,
      autoplay: true,
      autoplaySpeed: 2000,
        fade:true,
    });

    </script>
   <script src="https://maps.googleapis.com/maps/api/js?key={{key}}&libraries=places&types=cities&callback=activatePlacesSearch"async defer>

   </script>

                  </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

gym/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="shortcut icon" type="image/png" href="{{ url_for('static', filename='favicon.png') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>Cloud Fitness- {{ title }}</title>
    {% else %}
        <title>Cloud Fitness</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">Cloud Fitness</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                <a class="nav-item nav-link" href="{{ url_for('main.blog') }}">Blog</a>
            </div >
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                
              {% endif %}
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row" style="padding-top: 1%; width: 110%;">
        <div class="col-md-6">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
 <!--        <div class="col-md-3">
          <div class="content-section">
            <h3> Sick advertisements </h3>
            <p class='text-muted'> 
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div> -->
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

gym/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}